/*
-- Query: SELECT * FROM soccer.team
LIMIT 0, 1000

-- Date: 2022-12-30 16:18
*/
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (1,9987,673,'KRC Genk','GEN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (2,9993,675,'Beerschot AC','BAC');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3,10000,15005,'SV Zulte-Waregem','ZUL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (4,9994,2007,'Sporting Lokeren','LOK');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (5,9984,1750,'KSV Cercle Brugge','CEB');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (6,8635,229,'RSC Anderlecht','AND');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (7,9991,674,'KAA Gent','GEN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (8,9998,1747,'RAEC Mons','MON');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (10,9985,232,'Standard de LiÃ¨ge','STL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11,8203,110724,'KV Mechelen','MEC');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (12,8342,231,'Club Brugge KV','CLB');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (13,9999,546,'KSV Roeselare','ROS');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (14,8571,100081,'KV Kortrijk','KOR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (16,9996,111560,'Royal Excel Mouscron','MOU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (17,10001,681,'KVC Westerlo','WES');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (18,9986,670,'Sporting Charleroi','CHA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (614,9997,680,'Sint-Truidense VV','STT');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (1034,9989,239,'Lierse SK','LIE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (1042,6351,2013,'KAS Eupen','EUP');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (1513,1773,100087,'Oud-Heverlee Leuven','O-H');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (2004,8475,110913,'Waasland-Beveren','WAA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (2476,8573,682,'KV Oostende','OOS');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (2510,274581,111560,'Royal Excel Mouscron','MOP');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3457,10260,11,'Manchester United','MUN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3458,10261,13,'Newcastle United','NEW');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3459,9825,1,'Arsenal','ARS');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3460,8659,109,'West Bromwich Albion','WBA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3461,8472,106,'Sunderland','SUN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3462,8650,9,'Liverpool','LIV');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3463,8654,19,'West Ham United','WHU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3464,8528,1917,'Wigan Athletic','WIG');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3465,10252,2,'Aston Villa','AVL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3466,8456,10,'Manchester City','MCI');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3467,8668,7,'Everton','EVE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3468,8655,3,'Blackburn Rovers','BLB');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3469,8549,12,'Middlesbrough','MID');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3470,8586,18,'Tottenham Hotspur','TOT');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3471,8559,4,'Bolton Wanderers','BOL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3472,10194,1806,'Stoke City','STK');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3473,8667,1952,'Hull City','HUL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3474,9879,144,'Fulham','FUL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3475,8455,5,'Chelsea','CHE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (3476,8462,1790,'Portsmouth','POR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (4218,8658,88,'Birmingham City','BIR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (4225,8602,110,'Wolverhampton Wanderers','WOL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (4234,8191,1796,'Burnley','BUR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (4996,8483,1926,'Blackpool','BLA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (5744,10003,1960,'Swansea City','SWA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (5747,10172,15,'Queens Park Rangers','QPR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (5756,9850,1792,'Norwich City','NOR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (6504,8466,17,'Southampton','SOU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (6509,9798,1793,'Reading','REA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (7261,9826,1799,'Crystal Palace','CRY');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (7276,8344,1961,'Cardiff City','CAR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (8021,8197,95,'Leicester City','LEI');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (8779,8678,1943,'Bournemouth','BOU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (8784,9817,1795,'Watford','WAT');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9537,8583,57,'AJ Auxerre','AUX');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9538,9830,71,'FC Nantes','NAN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9539,9827,59,'Girondins de Bordeaux','BOR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9540,7819,210,'SM Caen','CAE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9541,9746,1738,'Le Havre AC','LEH');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9542,9831,72,'OGC Nice','NIC');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9543,8682,1739,'Le Mans FC','LEM');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9544,8689,217,'FC Lorient','LOR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9545,9748,66,'Olympique Lyonnais','LYO');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9546,9941,1809,'Toulouse FC','TOU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9547,9829,69,'AS Monaco','MON');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9548,9847,73,'Paris Saint-Germain','PSG');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9549,8481,1823,'AS Nancy-Lorraine','NAN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9550,8639,65,'LOSC Lille','LIL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9551,9851,74,'Stade Rennais FC','REN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9552,8592,219,'Olympique de Marseille','MAR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9553,9874,226,'FC Sochaux-MontbÃ©liard','SOC');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9554,9855,1805,'Grenoble Foot 38','GRE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9555,9873,110456,'Valenciennes FC','VAL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (9556,9853,1819,'AS Saint-Ã‰tienne','ETI');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (10300,8588,64,'RC Lens','LEN');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (10309,10249,70,'Montpellier HÃ©rault SC','MON');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (10312,4170,111376,'US Boulogne Cote D\'Opale','BOU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11074,108893,111989,'AC Arles-Avignon','ARL');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11076,8521,378,'Stade Brestois 29','BRE');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11817,8576,614,'AC Ajaccio','AJA');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11822,4087,111271,'Ã‰vian Thonon Gaillard FC','ETG');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (11825,9836,110569,'Dijon FCO','DIJ');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (12587,9837,379,'Stade de Reims','REI');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (12594,7794,58,'SC Bastia','BAS');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (12595,10242,294,'ES Troyes AC','TRO');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (13343,9747,62,'En Avant de Guingamp','GUI');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (14106,8550,68,'FC Metz','MET');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (14868,8121,1530,'Angers SCO','ANG');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (14876,6391,110316,'GFC Ajaccio','GAJ');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15617,9823,21,'FC Bayern Munich','BMU');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15618,9790,28,'Hamburger SV','HAM');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15619,8178,32,'Bayer 04 Leverkusen','LEV');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15620,9789,22,'Borussia Dortmund','DOR');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15621,10189,34,'FC Schalke 04','S04');
INSERT INTO `` (`id`,`team_api_id`,`team_fifa_api_id`,`team_long_name`,`team_short_name`) VALUES (15622,9904,485,'Hannover 96','HAN');
